### ISSUE TITLE
Button and Functional Area

### ISSUE THREAD

**Issue by syKevinPeng** [syKevinPeng/CSSA-MiniApp#4]
### Based on our home page design, start working on bottom part of the main page.

Use canvas to first draw static CSSA logo and then add dynamic drawing
Please refer to [SOURCE.MD](https://github.com/UMD-CSSA/CSSA-MiniApp/blob/dev/RESOURCES.md) for example canvas
DDL: Oct.13

**IMPORTANT: Before coding, checkout brach `btn_area` locally. Make sure that you commited and pushed to correct the branch.**

**Comment by jerryc05** [comment]
no longer valid, closing.
